# Generated by Django 4.2.17 on 2025-01-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(help_text='Separate each ingredient with comma', max_length=500),
        ),
    ]
